### ISSUE TITLE
Suggestion: Remove `triggerCharacters` that passed to registerCompletionItemProvider

### ISSUE THREAD

**Issue by hikerpig** [draivin/hsnips#12]
When setting `"editor.suggestOnTriggerCharacters": true` in vscode, and enable hsnips. I encounter a strange problem, vscode IntelliSense (TS/JS code suggestion) won't show, only snippets shown in completion suggestions.

Quoted [vscode documentation](https://code.visualstudio.com/api/references/vscode-api) on `registerCompletionItemProvider`:

> When trigger characters are being typed, completions are requested but only from providers that registered the typed character

Setting trigger character within the alphabet may block other completion item provider's results.

With triggerCharacters removed, multiple completion item providers can work together nicely.

**Comment by draivin** [comment]
Sorry for the delay on getting to this issue, I've been away for a while, I'll take a look into it, but as far as I remember vscode will not call the completion provider in many cases we would like it to when the characters are not set.

I'll have to look into it again, is there something in the linked issue that could be useful for me over here?

Thanks for the report.

**Comment by hikerpig** [comment]
Don't mind the linked issue. I just want the author come and see the explanation here.

Thanks for your work, a great inspiration.

**Comment by draivin** [comment]
So, I checked it over, and when you remove the completion characters it works just as you would expect when you type an alphanumerical character, with suggestions and automatic expansions.

The issue seems to happen when completing unusual characters, such as `.` or `/`, in those cases the key press will never be forwarded to the completion provider. I'll check if listening on document edits is a viable alternative so we can drop the completion item providers.
