### ISSUE TITLE
Snippet Variables?

### ISSUE THREAD

**Issue by JackYoungblood** [draivin/hsnips#16]
Is it possible to use [variables from the built in snippeting functionality](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets) within hsnips? If so, what's the syntax?

**Comment by draivin** [comment]
I believe they will expand as expected, with the same syntax, but if there is a dynamic block in the same line following the variable, the block may break.

This happens because the hsnips engine doesn't know the text that will replace the variable, so it can't correctly compute the region of the dynamic block that follows the variable. Perhaps that can be fixed by handling the replacement ourselves, but that is its own rabbit hole with implementing variable transforms.

I'll close the issue for now, but if you actually need a block following a variable, or perhaps if you want to access the variables from within code blocks, reopen this issue and I'll look into it.

**Comment by ArturoDent** [comment]
I tried a lot of combinations, like

```
snippet `fileName` "get fileName" A
``rv = ${file}``
endsnippet
```

Which result in an `(Unexpected token '{')`.  And I tried  with and without various escapes/double-escapes and nothing worked.  Nor does `${file}` alone expand.  It would be a powerful addition to HyperSnips.

**Comment by draivin** [comment]
Hi there, so reimplementing the full snippet syntax substitution would be an ordeal I'm not sure I'd be comfortable going through, but if there are a list of variables that you would be interested in having inside the dynamic snippet blocks let me know and I'll try to create an object with those that will be available during execution.

**Comment by gruvw** [comment]
Hi, the variable that I miss the most is `$TM_SELECTED_TEXT`.

**Comment by yfzhao20** [comment]
> Hi, the variable that I miss the most is $TM_SELECTED_TEXT.

This [Test](https://github.com/draivin/hsnips/issues/81#issuecomment-970168548) may provide you the solution.

---



> I tried a lot of combinations, like
> 
> ```
> snippet `fileName` "get fileName" A
> ``rv = ${file}``
> endsnippet
> ```
> 
> Which result in an `(Unexpected token '{')`. And I tried with and without various escapes/double-escapes and nothing worked. Nor does `${file}` alone expand. It would be a powerful addition to HyperSnips.

Add 
```js
const vscode = require("vscode");
var editor=vscode.window.activeTextEditor
var document=editor.document
```
between your `global` and `endglobal`, and use this in your snippet:`rv=document.fileName`
like this:
```js
snippet test "test" iA
``rv=document.fileName``
endsnippet
```
![1111](https://user-images.githubusercontent.com/80528249/141977120-7358ac01-c164-487e-bee8-ace68bc058dc.gif)

**Comment by draivin** [comment]
Closing this issue in favor of https://github.com/draivin/hsnips/issues/81
