### ISSUE TITLE
Is python support possible ?

### ISSUE THREAD

**Issue by medwatt** [draivin/hsnips#20]
I have to say I find this extension god-send really. The only problem is I have never used Javascript before. I'm already familiar with Python. I know that browsers can run Javascript code directly, but is there a possibility we can use Python instead of Javascript ?

**Comment by draivin** [comment]
Hi there, when creating the extension I chose to use javascript because vscode runs on electron, which can run javascript without installing any external programs, as opposed to python which would need an external installation.

I don't really want to add python support to this extension, as adding an external dependency really complicates stuff.

Also, I believe [this project](https://github.com/corvofeng/Vsnips) is more in line with a direct port of UltiSnips to vscode, but they chose instead to go with the code rewrite route, which I don't think is powerful enough for my use cases at least. Maybe you could check if it is powerful enough to run the python snippets you want to run.

**Comment by draivin** [comment]
Closing as it is not the goal for this extension.
