### ISSUE TITLE
`<tab>` does not trigger expansion of nested snippets

### ISSUE THREAD

**Issue by gruvw** [draivin/hsnips#42]
Related to [this](https://github.com/microsoft/vscode/issues/123353) VSCode issue.

When the HyperSnips extension is enabled, it becomes impossible to use nested completion: completion while being inside a snippet placeholder.

This is a bit frustrating as it is preventing snippet nesting (not only for .hsnips snippets but for any VSCode snippets)

### Steps to reproduce

(Don't forget to add the setting `"editor.suggest.snippetsPreventQuickSuggestions": false`)

Create a simple VSCode snippet:
```json
"Dash": {
    "prefix": "dash",
    "body": [
        "$1-$0"
    ]
}
```

(`|` is a future snippet placeholder, `<cursor>` is the current cursor position)

Without the HyperSnips extension, the behavior is as intended:  
Typing `dash<tab>dash<tab>` is nesting the two snippets resulting in `<cursor>-|-|`.

With the HyperSnips extension enabled:
Typing `dash<tab>dash<tab>` results in `dash-<cursor>`.

**Comment by draivin** [comment]
Hello, sorry for the delay in getting to this issue. So, what is the expected behavior here? Should we always insert a snippet on tab when the snippet selection screen is open? For now, you can change the `hsnips.nextPlaceholder` keyboard shortcut, by adding ` && !suggestWidgetVisible` to the `when` clause it should fix your particular issue.

Personally, I accept snippets using the enter key, this way there is no ambiguity between moving (tab) and accepting (enter), so I'm not sure what a good tradeoff would be (changing it to always insert on tab would personally annoy me), maybe give the user some configuration, or is adding the tip I gave above to the `README` good enough?

**Comment by draivin** [comment]
Just thought a little bit about it, and probably the better solution is making that behavior the default one and changing the shortcut on my end to reflect the way I do things. 😅

PS: Just did that in the latest hsnips version, closing this issue now!

**Comment by gruvw** [comment]
Hi, thanks for your answers! Your "tip" is working and solved the issue I had.

As it is the default behavior of VSCode, I would set the nested snippets expansion using `tab` to be enabled by default (what you just did). You could add a setting (or a "tip" in the `README`) to change this behavior if some users do not want it to be enabled.
