### ISSUE TITLE
Subtle context matching

### ISSUE THREAD

**Issue by gruvw** [draivin/hsnips#50]
Hello, I am currently testing the new context matching support and I found something that can be annoying for LaTeX users:

In math mode, the math scope is still active inside `\text{}` command...  
If I need to write a small text while writing an equation, all my snippets will automatically trigger.

I don't know if this can be solved or not as it has to do with TextMate scopes. If not, could we find a workaround ?

You can take a look at the Context § in <https://castel.dev/post/lecture-notes-1>.

**Comment by draivin** [comment]
Hi @gruvw, the cleanest way for this to be fixed would be for LaTeX-Workshop to update their syntax files so that the math environment wouldn't be active inside a `\text` command.

On our end, the best we can probably do is to create a vscode extension that [injects](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars) the relevant LaTeX grammar. The end result would be the same, but it would require one additional extension installation.

Unfortunately, my knowledge of textmate grammars isn't all that great (I'm barely able to syntax highlight the `.hsnips` files), so I'd have to take some time to find out how to do that.

**Comment by gruvw** [comment]
Ok...

I don't think that the solution is to create a special extension just for this purpose and I hope we don't need to go that way...

About pushing the problem to the next text nesting, I don't really see the point: if you are in text mode (within a math block), why would you nest a new `\text` context ?  
In short: `\text{test $x+3 \text{ test}$}` is the same as `\text{test $x+3$ test}`.  
At least for me, one level nesting would be enough.

I will create a new issue in the LaTeX Workshop repository to see what they can do about it.

**Comment by gruvw** [comment]
will be merged into main branch of LaTeX-Workshop extension
