### ISSUE TITLE
Why the error occurs?

### ISSUE THREAD

**Issue by pilgrimlyieu** [draivin/hsnips#67]
![](https://user-images.githubusercontent.com/80107081/129144730-2506e858-8180-4878-80da-6161f106a753.gif)

When I type `2.(2).`, it works normally. But when I type a fraction, it'll move a `}` to another place.

![](https://user-images.githubusercontent.com/80107081/129145419-e986a11e-d712-4a6d-9ceb-0044e8fc9a98.gif)

However, When I remove the placeholder, it works again.

**Comment by draivin** [comment]
This is a consequence of the first expansion of the snippet, as you are capturing a `}` it thinks you are trying to close the capture group. You can fix this by escaping the brackets inside the `m[1]` variable, that is, instead of `rv = m[1]` you should use something like `rv = m[1].replace(/\}/g, '\\}')`.

**Comment by pilgrimlyieu** [comment]
> This is a consequence of the first expansion of the snippet, as you are capturing a `}` it thinks you are trying to close the capture group. You can fix this by escaping the brackets inside the `m[1]` variable, that is, instead of `rv = m[1]` you should use something like `rv = m[1].replace(/\}/g, '\\}')`.

It works!1 Thanks alot!
