### ISSUE TITLE
v0.2.4 broke placeholders in return value

### ISSUE THREAD

**Issue by gruvw** [draivin/hsnips#97]
```
snippet `ab` "test" A
`` rv = "a $1 b" ``
endsnippet
```
Not working as intended in v0.2.4 but worked fine in v0.2.3.

**Comment by pilgrimlyieu** [comment]
same question

**Comment by pilgrimlyieu** [comment]
I modified the file "out\hsnippetInstance.js" as a temporary solution.

```js
blocks = blocks.map(s => s.replace(/\$/g, "\\$"));
```

to

```js
blocks = blocks.map(String);
```

**Comment by yfzhao20** [comment]
> I modified the file "out\hsnippetInstance.js" as a temporary solution.
> 
> ```js
> blocks = blocks.map(s => s.replace(/\$/g, "\\$"));
> ```
> 
> to
> 
> ```js
> blocks = blocks.map(String);
> ```

这相当于把上一个commit又改了回来，但是不明白原理是什么。
![image](https://user-images.githubusercontent.com/80528249/145561852-12c8a006-be0b-42b9-9e35-bc73de747c6a.png)

**Comment by draivin** [comment]
I'm currently a little torn about this issue, is it preferable to handle `$` by default as a snippet placeholder or as the character?

If we handle it as a placeholder, there is an inconsistency: after the first render of the snippet, any code block updates aren't able to change placeholders, and any `$` are parsed as the literal `$`. For this reason I believe we should by default handle it as the character, and introduce some special syntax for declaring placeholders.

I'm open to suggestions.

**Comment by gruvw** [comment]
Well without using the `rv` variable and using a regular snippet $ still works as a placeholder and I think we should be consistent across regular and js `rv` snippets.

**Comment by draivin** [comment]
The previous versions of hsnips lacked `rv` result consistency depending on when the code block was executed. Consider the following snippet:

```lua
snippet conditional "Conditional"
$1
``
if (t[0].length > 0) rv = '$2';
``
endsnippet
```

This snippet, even in the old version, would insert the string `$2` below the edit line as soon as the user typed something in the first placeholder, this happens because placeholders can only be inserted at the snippet initialization step, any latter and the string `$2` is just parsed as the literal.

Now look at the following snippet, that supposedly (syntactically) should behave the same:

```lua
snippet nonconditional "Non-conditional"
$1
``
rv = '$2';
``
endsnippet
```

This snippet, in the old version, would create a placeholder below the edit line, even though the syntax suggests it should do the same as the previous snippet. In the current version it inserts the string `$2`, the same behavior as above, maintaining syntax consistency.

Now, I consider this a greater consistency than we had before, but I also find it interesting to be able to dynamically insert placeholders in code blocks, but I believe we should have special syntax for this, so things are not ambiguous.

**Comment by draivin** [comment]
My own syntax suggestion is to inject a new variable to the code blocks called `snip`, to which we could add utility methods. So, to declare a tab stop with `snip` you would do something like this:
```lua
snippet nonconditional "Non-conditional"
$1
``
rv = `${snip.tabstop(2)}`;
``
endsnippet
```

**Comment by universemaster** [comment]
May I make a polite general suggestion.

Sometimes "breaking changes" are necessary and desirable. However, I really do think it would be very helpful if these breaking changes were clearly commuted and any manual mitigation actions were detailed. This way,  a user has the option to defer (or revert) an update until they have time/energy to make the manual changes.

For now, I have used the "previous versions" functionality of vscode to downgrade to 0.2.3, because I do not have the time right now to migrate my snippets.

But of course, I don't want to forget that you have created a great extension that I use hundreds of times a day, and love very much!

**Comment by gruvw** [comment]
> My own syntax suggestion is to inject a new variable to the code blocks called `snip`, to which we could add utility methods.

I am ok with this syntax as long as we can do (at least) the same things we could while using the old $ placeholder.
That means we would need a way to declare defaults values for a tabstop.

**Comment by draivin** [comment]
With respect to @universemaster comments, I agree in general that breaking peoples code is bad, but creating changelogs  (and publishing, and implementing the code to display a changelog on updates) is something I do not have the time for right now. As a stopgap measure I believe the issues (and discussion) sessions here are a good enough place for people to communicate breaking changes with each other, as happened here.

Either way, the new version of `hsnips` now accepts the syntax
```lua
snippet `ab` "test" A
`` rv = `a ${snip.placeholder(1, 'text')} b` ``
endsnippet
```
 and as such I'm closing this issue. 

Feel free to reply with any suggestions, but as I said, unfortunately my time is quite limited right now so I can't promise anything.

**Comment by yfzhao20** [comment]
So, that means I can not use `rv="a $1 b"` at `v0.2.7` ?

If so, maybe I have to overwrite my `.hsnips` file.🧐

**Comment by gruvw** [comment]
What do you mean by:
> it (currently) breaks the "tabstop text" feature

**Comment by sleepymalc** [comment]
I just migrate my setup from [HyperSnips for Math](https://marketplace.visualstudio.com/items?itemName=OrangeX4.hsnips) to [HyperSnips](https://marketplace.visualstudio.com/items?itemName=draivin.hsnips) since I find out that it supports math mode by `context`. But I immediately face the issue about this since I use [Hypersnips](https://marketplace.visualstudio.com/items?itemName=draivin.hsnips) to generate the grid of `table`, `pmatrix`, `bmatrix`, and `array` environment automatically by this. After some try-and-error, I get it works as expected. If anyone is interested, please see [here](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/blob/main/VSCode-setting/Snippets/latex.hsnips#L7-L47).

Note that it seems like it only supports **directly assigning `rv` with code**, rather than generating a string from [javascript function](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/commit/3cc612981e678f3b36f5560097bb06a1b6230dfb#diff-e7219567442c0ccd2227db3073a0207a5affb7405ae8d031dbc4d025cea5481dR8-R22) and passing it back to `rv` as [this example](https://github.com/sleepymalc/VSCode-LaTeX-Inkscape/commit/3cc612981e678f3b36f5560097bb06a1b6230dfb#diff-e7219567442c0ccd2227db3073a0207a5affb7405ae8d031dbc4d025cea5481dR91-R96) I previously implemented. Though I understand the technical difficulties, I think this should be mentioned in the [README](https://github.com/draivin/hsnips/blob/master/README.md) to bring some attention.
